/** All user-facing copy. Plain, short, present tense. Says "described" and "on/off" — never the blocklisted words (see docs/decisions/0002-wording.md). */
export const strings = {
  firstRun: [
    { title: 'Described plays every film with audio description.', body: "It's on now.", cta: 'Next' },
    { title: 'Press Menu while watching.', body: 'Change the voice, captions, or turn description off.', cta: 'Next' },
    { title: 'Extended mode pauses the film when there is a lot to describe.', body: 'Keep it on?', cta: 'Keep on', alt: 'Turn off' },
  ],
  home: { continue: 'Continue watching', newly: 'Newly described', all: 'All titles', playWithAd: 'Play with description', play: 'Play', myList: 'My list' },
  title: {
    hearSample: 'Hear a sample', stopSample: 'Stop the sample', samplePlaying: 'Playing a sample', playWithout: 'Play without description',
    processing: (min: number) => `We're still describing this film — about ${min} minutes left.`, more: 'More', close: 'Close',
    captions: (kind: string) => `Captions: ${kind} ▾`,
  },
  badge: { ad: 'AD', sdh: 'Rich captions', extended: (n: number) => `Extended: ${n} ${n === 1 ? 'pause' : 'pauses'}` },
  minutes: (n: number) => `${n} min`,
  /** Spoken labels (aria-label): the purpose of each focusable, not its role. */
  a11y: {
    playWithAd: (name: string) => `Play ${name} with audio description`,
    playWithout: (name: string) => `Play ${name} without description`,
    listAdd: (name: string) => `Add ${name} to My list`,
    listRemove: (name: string) => `Remove ${name} from My list`,
    open: (name: string, facts: string[]) => [`Open ${name}`, ...facts].join('. '),
    minutes: (n: number) => `${n} minutes`,
    resume: (min: number) => `${min} minutes watched`,
    ad: 'Audio description',
    sample: (name: string) => `Hear a sample of the description voice for ${name}`,
    sampleHint: 'Plays about 20 seconds over the poster',
    stopSample: 'Stop the sample',
    captions: (kind: string) => `Captions: ${kind}`,
    captionsHint: 'Press to change captions',
    more: (name: string) => `Read the full synopsis of ${name}`,
    close: 'Close the synopsis',
    retry: 'Try the library again',
    rail: (label: string) => `Go to ${label}`,
  },
  player: {
    statusOn: (voice: string, cap: string) => `Description on · ${voice} · ${cap}`, statusOff: (cap: string) => `Description off · ${cap}`, captionsOff: 'Captions off',
    loading: 'Loading…', error: 'Playback stopped. Press Select to try again, Back for the title.', extendedBar: 'Describing…',
    ended: 'The end. Press Select to watch again, Back for the title.',
    surface: (name: string) => `Play or pause ${name}`, surfaceHint: 'Left and right skip 10 seconds. Menu changes audio and captions.',
    position: (at: string, of: string) => `${at} of ${of}`,
  },
  tracks: {
    heading: 'Audio & captions', audio: 'Audio', original: 'Original', ad: (voice: string) => `Audio description (${voice})`, captions: 'Captions', off: 'Off', plain: 'Captions', rich: 'Rich captions', descText: 'Description text', extended: 'Extended mode', announceOn: 'Description on', announceOff: 'Description off',
    on: 'On', offState: 'Off',
    a11y: {
      original: 'Audio: Original, no description', ad: (voice: string) => `Audio: Audio description, voice ${voice}`,
      off: 'Captions off', plain: 'Captions: Captions, dialogue only', rich: 'Captions: Rich captions, with sounds and music', descText: 'Captions: Description text',
      extendedOn: 'Extended mode is on. Press to turn it off', extendedOff: 'Extended mode is off. Press to turn it on',
    },
  },
  settings: { adDefault: 'Description on by default', voice: 'Voice', hearIt: 'Hear it', extended: 'Extended mode', capSize: 'Caption size', capStyle: 'Caption style', reset: 'Show first-run again', about: 'About & licenses' },
  offline: 'Can\u2019t reach the library. Check the network and press Select to retry.',
  retry: 'Try again',
  rail: { home: 'Home', described: 'Described', list: 'My list', settings: 'Settings' },
}
