import { playLink, titleLink } from '@described/contracts'

/**
 * Fire TV catalog feed (DESC-008). Fire OS has no runtime catalog API: titles reach Fire TV search, browse and
 * "Alexa, play …" only through catalog integration, a file Amazon ingests once the app is accepted as a catalog
 * partner. See docs/platform/fire-os-bindings.md §1 for the process and why this is a draft.
 *
 * Shape: Catalog Data Format (CDF) — https://developer.amazon.com/docs/catalog/all-elements.html
 * Element names and order are written from Amazon's CDF examples, NOT validated against the XSD (developer.amazon.com
 * is unreachable from the build environment). Amazon now calls CDF legacy and asks new partners for EMBER
 * (https://developer.amazon.com/docs/catalog/ember-catalog-integration-overview.html); everything EMBER needs is in
 * `FeedTitle`, so switching is a change to `movie()` only. Validate against the XSD Amazon sends before uploading.
 *
 * The deep links are not CDF elements: Fire TV launches a catalog title by passing its ID to the app's launcher
 * integration (https://developer.amazon.com/docs/catalog/integrate-with-launcher.html). Each Movie carries them as
 * a comment so the ID → deep link mapping is reviewable in the file itself.
 */
export interface FeedTitle {
  slug: string; name: string; year: number | null; durationS: number | null; synopsis: string | null
  posterUrl: string | null
}
export interface FeedOptions {
  /** The <Partner> value Amazon assigns; "Described" until then. */
  partner?: string
  locale?: string
  /** ISO 3166 codes for <Territories>. Sintel and the other titles are CC-BY: free everywhere. */
  territories?: string[]
}

export const CDF_NAMESPACE = 'http://www.amazon.com/FireTv/2014-04-11/ingestion'
export const CDF_VERSION = 'FireTv-v1.3'

export function escapeXml(s: string): string {
  // Characters XML 1.0 forbids outright are dropped; the five specials are escaped.
  // eslint-disable-next-line no-control-regex
  return s.replace(/[\u0000-\u0008\u000B\u000C\u000E-\u001F￾￿]/g, '')
    .replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;').replace(/'/g, '&apos;')
}
/** XML comments may not contain "--". Slugs cannot, but be safe. */
const comment = (s: string) => `<!-- ${s.replace(/--+/g, '-')} -->`

function movie(t: FeedTitle, o: Required<FeedOptions>): string {
  const lines = [
    `    <Movie>`,
    `      ${comment(`launch: ${playLink(t.slug)} · details: ${titleLink(t.slug)}`)}`,
    `      <ID>${escapeXml(t.slug)}</ID>`,
    `      <Title locale="${escapeXml(o.locale)}">${escapeXml(t.name)}</Title>`,
    `      <Offers>`,
    `        <FreeOffer>`,
    `          <Regions><Territories>${escapeXml(o.territories.join(' '))}</Territories></Regions>`,
    `        </FreeOffer>`,
    `      </Offers>`,
  ]
  if (t.synopsis) lines.push(`      <Synopsis>${escapeXml(t.synopsis)}</Synopsis>`)
  if (t.year && t.year > 0 && t.year <= 9999) lines.push(`      <ReleaseDate>${String(t.year).padStart(4, '0')}-01-01T00:00:00</ReleaseDate>`) // xs:dateTime needs a 4-digit year
  if (t.durationS) lines.push(`      <RuntimeMinutes>${Math.max(1, Math.round(t.durationS / 60))}</RuntimeMinutes>`)
  if (t.posterUrl) lines.push(`      <ImageUrl>${escapeXml(t.posterUrl)}</ImageUrl>`)
  lines.push(`    </Movie>`)
  return lines.join('\n')
}

/** The catalog file for the given published titles, in a stable order (by slug) so regenerating shows a clean diff. */
export function renderFireTvCatalog(titles: FeedTitle[], options: FeedOptions = {}): string {
  const o: Required<FeedOptions> = { partner: 'Described', locale: 'en-US', territories: ['US'], ...options }
  const works = [...titles].sort((a, b) => a.slug.localeCompare(b.slug)).map((t) => movie(t, o))
  return [
    `<?xml version="1.0" encoding="UTF-8"?>`,
    comment(`Draft Fire TV catalog (CDF ${CDF_VERSION}) generated by Described. Validate against Amazon's XSD before upload.`),
    `<Catalog xmlns="${CDF_NAMESPACE}" version="${CDF_VERSION}">`,
    `  <Partner>${escapeXml(o.partner)}</Partner>`,
    `  <Works>`,
    ...works,
    `  </Works>`,
    `</Catalog>`,
    '',
  ].join('\n')
}
